@startuml
title SpringBoot動作概念
クライアント -> "サーバ/Spring": HTTP リクエスト
"サーバ/Spring" -> コントローラ: URL/HTTPメソッドに応じて振り分け
コントローラ -> サービス: 呼び出し
サービス -> サービス: 業務処理
サービス -> DAO: DBアクセス
DAO -> サービス: 
サービス -> コントローラ: 処理結果返却
コントローラ -> "サーバ/Spring": レスポンスオブジェクト
"サーバ/Spring" -> クライアント: HTTP レスポンス
@enduml
